### PR TITLE
added random seed functionality

### PR DESCRIPTION
**Pull request by reinhold-willcox**
Cleaned up several features.

- created run_sw.py file in the source code, which contains the parts of the interface file which do not require user input (the SW calls and configure_code_run)
- added RANDOM_SEED global so that the seed can be passed around and incremented correctly
- added --random-seed as first parameter in the gridfiles
- added a stroopwafel_interface file (which will later be removed and put into COMPAS) with associated stoopwafel_dev softlink to make testing easier.

### CODE REVIEW

**Comment by stellarphysicsandpopulations** [comment]
Wow, Reinhold!  Sounds great.   I haven't read the code yet, but I like the description. Will try to review ASAP (but this is a busy week).

**Comment by reinhold-willcox** [comment]
No rush, Stephen. Testing is definitely a good idea: I found (and fixed) a bug already, with the way arbitrary base seeds are set.

**Review by LiekeVanSon — COMMENTED** [review]
Looks great Reinhold! Does the random seed functionality allow for reproduction of the same systems based purely on the random seed? Or would you still have to resubmit a grid file with initial conditions?

**Review by LiekeVanSon — CHANGES_REQUESTED** [review]
In stroopwafel/run_sw.py, line 63 should be uncommented, line 64 removed (the None's in the initialize function cause it to crash for a non-MC run)

Keys need to be updated to newest COMPAS, i.e. Mass_2 ==> Mass(2)

**Comment by floriskummer** [comment]
Hi Reinhold, sorry for getting back to you so late. Thanks for helping us with the improvements :). I like the idea of the extra run_sw file to hide some of the interface code, and we could probably move even some more code there. I could successfully run MC simulations, however in order to run with AIS it still needed some updates: the interesting and rejected systems functions in the interface still use the old grid notation and in utils.py there are some more constants (apart from “RANDOM_SEED”) that should be preceded by “constants.” (I assume you had a good reason to change the way of importing the constants file). 

One thing about calling the sw_object functions in the run_sw.py file (something Stephen and I only found out recently): when running mc_only, it is important to still include the “rejected_systems” method. Otherwise you’ll get different weighted distributions between STROOPWAFEL and MC simulations. It should also not be necessary to include the “if not mc_only” statement. The stroopwafel code already takes care of that internally by not entering the next phases when passing the mc_only=True option (shouldn’t really matter that much, but looks a little bit cleaner I guess).

Last small point I had is about the “num_per_core” in the interface. I think we originally didn’t use a very precise term to describe it. It could better be described with “num_per_batch”, which means it wouldn’t be very desirable to set it to num_systems/num_cores, as you would get very large batch sizes, which negatively affects the performance of stroopwafel (for MC it is perfectly fine though). 

It’s very good to have you thinking about this too, and experimenting with ways to improve things.  Maybe we could discuss again all together after the holidays?

**Comment by reinhold-willcox** [comment]
Thanks @LiekeVanSon and @floriskummer for your feedback!

I've been making a few other changes with the help of @themikelau, so I'll incorporate your suggestions into those and push up a new PR. I think we are nearing the point where we can finalize these changes, push to the pip version, and export the stroopwafel_interface into compas!

To address your specific comments:

> Looks great Reinhold! Does the random seed functionality allow for reproduction of the same systems based purely on the random seed? Or would you still have to resubmit a grid file with initial conditions?

@LiekeVanSon That's a good point that Mike brought up too. In this version, the random seed is passed to COMPAS, but stroopwafel sampling is done independently, so running SW twice would produce different grid files. The upcoming changes will include a call to `np.random.seed(random_seed_base)`, so that the same seed generates SW input and COMPAS random variables. I expect that will resolve this issue. 


> Hi Reinhold, sorry for getting back to you so late. Thanks for helping us with the improvements :). I like the idea of the extra run_sw file to hide some of the interface code, and we could probably move even some more code there. I could successfully run MC simulations, however in order to run with AIS it still needed some updates: the interesting and rejected systems functions in the interface still use the old grid notation and in utils.py there are some more constants (apart from “RANDOM_SEED”) that should be preceded by “constants.” (I assume you had a good reason to change the way of importing the constants file).

@floriskummer True, I have only been testing with mc_only, so thanks for letting me know. I've fixed the grid notation issues but please let me know if there are other oddities related to non-mc sampling. Regarding the RANDOM_SEED, it was an oversight that I removed the call for the other random variables. It was a bit finicky getting the call right, since most of the constants are truly constant (while the RANDOM_SEED really needs to be treated as a class attribute), but I think I've managed this.

> One thing about calling the sw_object functions in the run_sw.py file (something Stephen and I only found out recently): when running mc_only, it is important to still include the “rejected_systems” method. Otherwise you’ll get different weighted distributions between STROOPWAFEL and MC simulations. It should also not be necessary to include the “if not mc_only” statement. The stroopwafel code already takes care of that internally by not entering the next phases when passing the mc_only=True option (shouldn’t really matter that much, but looks a little bit cleaner I guess).

That's good to know. I've removed the statement, but will need to do some testing to make sure it all still works. 

> Last small point I had is about the “num_per_core” in the interface. I think we originally didn’t use a very precise term to describe it. It could better be described with “num_per_batch”, which means it wouldn’t be very desirable to set it to num_systems/num_cores, as you would get very large batch sizes, which negatively affects the performance of stroopwafel (for MC it is perfectly fine though).

I agree, and I have also been confused by this naming. I've changed the variable name from cores to batches everywhere it comes up, but I'm not sure what to set for a default value, or how best to communicate to users how to set this. Is it only valid for non-mc runs? Should there be a different default for mc or non-mc?

> It’s very good to have you thinking about this too, and experimenting with ways to improve things. Maybe we could discuss again all together after the holidays?

I would be happy to discuss this whenever. Ping me offline when you are back from your vacation and we can setup a time. I'm keen to learn how to use the non-mc sampling at some point. @floriskummer Have you made progress with the documentation?

**Comment by reinhold-willcox** [comment]
PR #7 supersedes this, so I'm closing this PR

**Pull request closed without merging**
