### PR TITLE
Grids fix

### PR DESCRIPTION
**Pull request by reinhold-willcox**
Fixes to the grid outputting to align with recent changes in COMPAS.

### CODE REVIEW

**Comment by stellarphysicsandpopulations** [comment]
Ah! Amazing, well done Reinhold.  Thank you!  That was on my personal to-do list, but apparently sometimes if I'm lazy then wonderful people like you *do* solve my problems for me!  

(I’m curious to try sampling in physical parameters too… not to build a population with a distribution of physics, but hopefully as an efficient way to explore physics variations.)

(In principle I don’t know whether we should move the COMPAS-specific utilities to being associated with the COMPAS interface, in the COMPAS repository rather than with the statistical parts. But we can talk about code locations later.)

Thank you again,

Stephen

**Comment by reinhold-willcox** [comment]
@stellarphysicsandpopulations Oh, Stephen, that's you! I was wondering about that - I think Ilya tagged you in a few COMPAS posts.

Yes, I agree, I was chatting with Floor about that earlier. I think it is much more straightforward to do that now with Jeff's latest changes, but we can discuss the implementation later.

Would you mind reviewing this PR?

**Review by stellarphysicsandpopulations — APPROVED** [review]
This is great, Reinhold.  I suppose I might have been cautious and kept backwards compatibility for now (e.g., have kept generate_grid_old for people using old COMPAS versions, or used generate_grid_newformat for this), but let's move fast and assume people will want to use new COMPAS (since there are many bugfixes too).  Yes, great.  I'll ask Floris to test....

**Comment by stellarphysicsandpopulations** [comment]
Extra comment:
   In the end, this function probably wants to either be:
(1) COMPAS-specific (if in the SW distribution)
(2) moved to the COMPAS package, along with the COMPAS-specific interface (if/when I streamline the COMPAS interface), so that COMPAS developers can more easily make sure to keep compatibility by maintaining this.

**Comment by reinhold-willcox** [comment]
You mean the file stroopwafel_rundev.py ? Yes, this should absolutely end up in the COMPAS repo. I've been leaving it in SW for now since changes to the interface have been moving in parallel with changes to the source code, but the end goal is to add it to COMPAS defaults/ and replace pythonSubmit.

**Comment by stellarphysicsandpopulations** [comment]
Just for the record, Floris tested and it seems to work very well. So thanks again, Reinhold.

**Pull request merged**
